import { useEffect, useState } from "react";
import Header from "@/components/Header";
import { ArrowLeft, Search, Book, Mail } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { cn } from "@/lib/utils";

// ------------------------------------------------------------------
// THE GLOSSARY DATA (COMPREHENSIVE - 60+ TERMS)
// ------------------------------------------------------------------
type Term = {
  term: string;
  def: string;
  category: "Roles" | "Finance" | "Distribution" | "Legal" | "The Math" | "Production";
};

const TERMS: Term[] = [
  // --- FINANCE ---
  { term: "Above the Line (ATL)", def: "The costs for the 'Creative' elements: Writer, Director, Producer, and Principal Cast. These are usually fixed fees negotiated upfront.", category: "Finance" },
  { term: "Accrual Accounting", def: "An accounting method where expenses are recorded when incurred (not when paid), and interest accumulates from day one.", category: "Finance" },
  { term: "Advance", def: "An upfront cash payment (Minimum Guarantee) given by a distributor or financier. This is recouped from future revenue before profit sharing begins.", category: "Finance" },
  { term: "Back End", def: "Net profits generated by the film that are payable to equity participants *after* all recoupment and expenses. Also called 'the backend' or 'net profit participation.'", category: "Finance" },
  { term: "Below the Line (BTL)", def: "The costs for the 'Physical' production: Crew, Equipment, Locations, Insurance, Food, Post-Production. This is the hard cost of making the movie.", category: "Finance" },
  { term: "Breakeven", def: "The exact gross revenue number needed to pay back all debts, equity (plus premium), fees, and expenses. Below this number, investors lose money. Above it, net profits begin.", category: "Finance" },
  { term: "CAM (Collection Account Management)", def: "A neutral third party that receives revenue and distributes it according to the waterfall. Takes ~1% off the top. Protects you from distributors holding cash.", category: "Finance" },
  { term: "Capped Expenses", def: "A negotiated limit on how much a distributor/agent can deduct for marketing and deliverables before paying you. This is critical protection.", category: "Finance" },
  { term: "Completion Bond", def: "An insurance policy that guarantees the film will be finished and delivered. Banks require this before lending Senior Debt. The bonder can take over the film if you go over budget.", category: "Finance" },
  { term: "Contingency", def: "An emergency buffer (usually 10% of the budget) required by bond companies and lenders. You should plan to spend it, but hope you don't.", category: "Finance" },
  { term: "Corridor (Producer's Corridor)", def: "A small percentage of first-dollar gross reserved for the producer, paid *before* the distributor recoups expenses. This is rare and powerful.", category: "Finance" },
  { term: "Debt", def: "Funding provided to the production of the film that must be paid back with interest. Senior Debt (banks) is paid first. Gap/Mezzanine is paid second.", category: "Finance" },
  { term: "Deferments", def: "Fees (producer, director, cast) that are delayed until *after* the film makes money. These sit in the waterfall after investors recoup.", category: "Finance" },
  { term: "Equity", def: "Investment for ownership. The riskiest money (paid last in the waterfall), but gets a share of the profits forever. Usually comes with a 'premium' (10-20%).", category: "Finance" },
  { term: "Gap Financing / Mezzanine", def: "High-interest loans that cover the 'gap' between the bank loan and the equity. Higher risk = higher reward (interest rates of 12-18%).", category: "Finance" },
  { term: "Minimum Guarantee (MG)", def: "An upfront cash advance paid by a distributor for the rights to your film. This is the 'bird in the hand' money. Often the ONLY money you'll see.", category: "Finance" },
  { term: "Overhead Fees", def: "A flat fee (often 10-15%) distributors charge for 'office expenses' on top of their commission. This is pure profit for them. Fight to cap or remove it.", category: "Finance" },
  { term: "P&A (Prints & Advertising)", def: "The money spent to market and distribute the film. In a traditional deal, the distributor spends this and recoups it *before* paying the producer.", category: "Finance" },
  { term: "Premium", def: "A bonus percentage (usually 10-20%) paid to equity investors on top of their principal before net profits begin. If they invested $100K, they get $120K back first.", category: "Finance" },
  { term: "Recoupment", def: "The point at which an investor gets their initial principal back. 'ROI' (Return on Investment) happens only *after* recoupment.", category: "Finance" },
  { term: "ROI (Return on Investment)", def: "The percentage profit made on the initial cash. Example: 120% ROI means they got their money back + 20%.", category: "Finance" },
  { term: "Senior Debt", def: "Bank loans that are paid back first in the waterfall. Lowest risk, lowest interest (8-12%). Often secured against Tax Credits or Pre-sales.", category: "Finance" },
  { term: "Soft Money", def: "Funding that doesn't need to be paid back directly or is easily recouped. Examples: Tax Credits, Grants, Crowdfunding. The holy grail.", category: "Finance" },
  { term: "Tax Credits", def: "Cash rebates from governments (e.g., UK, Georgia, Canada) to incentivize filming. Can be used as collateral for Senior Debt. Often 25-40% of local spend.", category: "Finance" },
  { term: "Waterfall", def: "The strict order of priority in which revenue is distributed. Money fills the top buckets (Debt, Expenses) before trickling down to the bottom (Net Profit). You are at the bottom.", category: "The Math" },

  // --- LEGAL / DEALS ---
  { term: "Acquisition Price", def: "The gross amount a distributor pays to buy the rights to the film. This happens *before* they take their sales commission.", category: "Legal" },
  { term: "Cross-Collateralization", def: "A trap where a distributor uses the profits from your movie to pay for the losses of *another* movie in their library. Always require 'Single Picture Accounting.'", category: "Legal" },
  { term: "Favored Nations (MFN)", def: "A clause ensuring fairness. It says: 'If you give anyone else a better deal (more money, better credit), you have to give it to me too.'", category: "Legal" },
  { term: "Holdbacks", def: "Restrictions preventing you from releasing the film in certain territories or media until the distributor's window expires.", category: "Legal" },
  { term: "License", def: "The right to exploit the film for financial gain in a specific territory, medium, or time period. Every other clause in a contract is limiting this license.", category: "Legal" },
  { term: "Pari Passu", def: "Latin for 'On Equal Footing.' When two investors in the same tier get paid back at the same time, proportional to their investment amount.", category: "Legal" },
  { term: "Pay or Play", def: "A guarantee that talent gets paid their fee even if the movie gets cancelled or they are replaced. A sign of A-list leverage.", category: "Legal" },
  { term: "Points (Backend Points)", def: "Percentage ownership of the backend (Net Profit). '5 Points' = 5% of the Producer's Pool. Talent often negotiates for these.", category: "Legal" },
  { term: "Territory", def: "The geographic region where a distributor has the right to exploit the film. Can be as small as 'French Canada' or as large as 'Worldwide.'", category: "Legal" },
  { term: "Term", def: "The length of time a distribution contract is in place. For most independent film deals, the term is 5-10 years.", category: "Legal" },

  // --- ROLES ---
  { term: "Completion Guarantor", def: "The insurance company that issues the Completion Bond. They can take over your film if you go over budget or fall behind schedule.", category: "Roles" },
  { term: "Executive Producer (EP)", def: "Usually the person who found the money or the script. They rarely handle physical production. In indie film, 'EP' is often the title given to a major investor.", category: "Roles" },
  { term: "Line Producer", def: "The CEO of the physical production. They manage the budget, the schedule, and the crew. They protect the 'Below the Line' costs.", category: "Roles" },
  { term: "Sales Agent", def: "The broker who represents your film to distributors globally. They take a commission (10-25%) and charge expenses. A good one is worth their weight in gold.", category: "Roles" },
  { term: "Producer's Rep", def: "An advisor who helps producers navigate sales, distribution, and festival strategy. They work for a flat fee or a percentage of the sale.", category: "Roles" },

  // --- DISTRIBUTION ---
  { term: "Acquisition", def: "The act of a distributor buying the rights to a finished film, typically at a film festival (Sundance, Cannes, Toronto).", category: "Distribution" },
  { term: "AVOD (Ad-Based VOD)", def: "Streaming platforms that are free for users but show ads (Tubi, Pluto TV, Freevee). Revenue is split based on views.", category: "Distribution" },
  { term: "Day and Date", def: "Releasing a film in theaters and on VOD (Video on Demand) on the exact same day. Good for marketing efficiency, bad for theater chains.", category: "Distribution" },
  { term: "Four-Wall", def: "The act of renting theaters yourself to screen your film. You cover all costs and keep all revenue. High risk, high reward.", category: "Distribution" },
  { term: "Geo-Filtering", def: "Technology that restricts online access to viewers in specific territories. Required for international licensing deals.", category: "Distribution" },
  { term: "Gross Receipts", def: "Total revenue collected by the distributor from all sources before any deductions. This is the top of the waterfall.", category: "Distribution" },
  { term: "Net Receipts", def: "Revenue remaining after the distributor deducts their fees and expenses. This is what flows into the producer's waterfall.", category: "Distribution" },
  { term: "Output Deal", def: "A contract where a distributor agrees to release multiple films from a producer over time, often with better terms than single-picture deals.", category: "Distribution" },
  { term: "Pre-Sales", def: "Sales of distribution rights made *before* the film is completed, based on the script, cast, and director. Used to secure production financing.", category: "Distribution" },
  { term: "Revenue Share", def: "A deal where the distributor splits revenue with the producer after recouping their expenses. Typically 50/50 or 60/40 (in distributor's favor).", category: "Distribution" },
  { term: "Sales Commission", def: "The fee (10-25%) charged by the Sales Agent on every dollar they generate. This comes off the top before expenses.", category: "Distribution" },
  { term: "SVOD (Subscription VOD)", def: "Streaming platforms where users pay a monthly fee (Netflix, Hulu, Amazon Prime). Licensing fees are typically flat, not per-view.", category: "Distribution" },
  { term: "TVOD (Transactional VOD)", def: "Platforms where users rent or buy individual titles (iTunes, Vudu). You get a percentage of each transaction.", category: "Distribution" },
  { term: "Windowing", def: "The strategy of releasing in stages (Theatrical → Airline → VOD → Subscription Streaming) to maximize price discrimination. Each 'window' is exclusive.", category: "Distribution" },

  // --- PRODUCTION ---
  { term: "Call Sheet", def: "The daily schedule distributed to cast and crew listing call times, locations, and scene numbers to be shot.", category: "Production" },
  { term: "Deliverables", def: "The materials (master files, metadata, closed captions, key art) a producer must provide to a distributor before receiving payment.", category: "Production" },
  { term: "DCP (Digital Cinema Package)", def: "The encrypted, high-quality file format used to project films in commercial theaters.", category: "Production" },
  { term: "E&O Insurance (Errors & Omissions)", def: "Insurance that protects against lawsuits for copyright infringement, libel, or other legal claims. Distributors require this.", category: "Production" },
  { term: "Key Art", def: "The main poster/marketing image for a film. Distributors often require multiple versions (theatrical, streaming, international).", category: "Production" },
  { term: "One Sheet", def: "A one-page marketing document with the film's logline, cast, crew, and sales contact info. Used at film markets and festivals.", category: "Production" },
  { term: "Wrap", def: "The completion of principal photography. 'It's a wrap!' means the last shot of the shoot day (or the entire production) is done.", category: "Production" },

  // --- THE MATH (Additional) ---
  { term: "Adjusted Gross", def: "Gross receipts minus only co-op advertising costs. A rare, producer-friendly deal structure where distribution expenses aren't deducted.", category: "The Math" },
  { term: "First Dollar Gross", def: "The most advantageous participation. You get paid from the very first dollar of revenue, before *any* deductions. Only A-listers get this.", category: "The Math" },
  { term: "Net Profit (Producer's Pool)", def: "The remaining money after *all* debts, fees, expenses, and equity recoupment. Typically split 50/50 between Investors and Producers.", category: "The Math" },
  { term: "Payment Waterfall", def: "A visual or contractual representation of how money flows from stakeholder to stakeholder, in strict order of priority.", category: "The Math" },
];

// Sort alphabetically by term
TERMS.sort((a, b) => a.term.localeCompare(b.term));

const Glossary = () => {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const filteredTerms = TERMS.filter(t => 
    t.term.toLowerCase().includes(searchTerm.toLowerCase()) || 
    t.def.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <>
      <Header />
      <div className="min-h-screen bg-bg-void text-text-primary pt-24 pb-12 px-4 md:px-8 font-sans">
        <div className="max-w-3xl mx-auto space-y-8 animate-fade-in">
          
          {/* Header */}
          <div className="flex flex-col gap-6 border-b border-border-default pb-8">
            <div className="flex items-center gap-2 text-gold mb-2">
              <Book className="w-5 h-5" />
              <span className="text-xs font-bold uppercase tracking-widest">The Black Book</span>
            </div>
            
            <h1 className="text-5xl md:text-6xl font-bebas text-white tracking-wide">
              Protocol <span className="text-gold">Glossary</span>
            </h1>
            
            <p className="text-xl text-text-mid leading-relaxed max-w-2xl">
              The film industry uses jargon to keep outsiders out. This is your decoder ring.
              Knowing these terms is the difference between looking like a novice and looking like a closer.
            </p>

            {/* Search Bar */}
            <div className="relative max-w-md">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-text-dim" />
              </div>
              <input
                type="text"
                placeholder="Search 60+ terms..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="block w-full pl-10 pr-3 py-3 border border-border-subtle rounded-md leading-5 bg-bg-elevated text-text-primary placeholder-text-dim focus:outline-none focus:border-gold/50 focus:ring-1 focus:ring-gold/20 sm:text-sm transition-all"
              />
            </div>
          </div>

          {/* Terms List */}
          <div className="grid gap-4">
            {filteredTerms.length === 0 ? (
              <div className="py-12 text-center text-text-dim">
                No terms found for "{searchTerm}"
              </div>
            ) : (
              filteredTerms.map((item, idx) => (
                <div 
                  key={idx}
                  className="group bg-bg-surface border border-border-default hover:border-gold/30 rounded-lg p-6 transition-all duration-200"
                >
                  <div className="flex flex-col md:flex-row md:items-baseline gap-2 md:gap-4 mb-2">
                    <h3 className="text-xl font-bold text-white group-hover:text-gold transition-colors">
                      {item.term}
                    </h3>
                    <span className="text-[10px] uppercase tracking-wider text-text-dim bg-bg-elevated px-2 py-1 rounded w-fit">
                      {item.category}
                    </span>
                  </div>
                  <p className="text-text-mid leading-relaxed text-sm md:text-base">
                    {item.def}
                  </p>
                </div>
              ))
            )}
          </div>

          {/* Footer */}
          <div className="pt-12 border-t border-border-default space-y-6">
            <div className="flex flex-col items-center gap-4 text-center">
              <div className="flex items-center gap-2 text-gold">
                <Mail className="w-4 h-4" />
                <span className="text-xs font-bold uppercase tracking-widest">Questions or Corrections?</span>
              </div>
              <p className="text-sm text-text-mid max-w-md">
                This glossary is a living document. If you spot an error or want to suggest a term, email us:
              </p>
              <a 
                href="mailto:thefilmmaker.og@gmail.com" 
                className="text-gold hover:text-gold-bright transition-colors text-sm font-mono"
              >
                thefilmmaker.og@gmail.com
              </a>
            </div>

            <div className="flex justify-center pt-4">
              <button 
                onClick={() => navigate(-1)} 
                className="flex items-center gap-2 text-text-dim hover:text-gold transition-colors uppercase tracking-widest text-xs font-bold"
              >
                <ArrowLeft className="w-4 h-4" />
                Return
              </button>
            </div>
          </div>

        </div>
      </div>
    </>
  );
};

export default Glossary;
